### PR TITLE
Issues 748

### LINKED ISSUE #748: Error Failed to initially fetch USD prices
Logs: https://www.notion.so/limechain/Ticket-hashport-validator-issues-748-0bd778af6f7a4b858cd15e7291deecc2

### PR DESCRIPTION
**Pull request by Coiling-Dragon**
**Detailed description**:
- Add USD price cache fallback in situations, where fetching it fails.
- Add default minimum amount, to be used as a fallback for error in calculations ( previously caused  by USDprice == 0 )
- Add tests for the above functionalities

**Which issue(s) this PR fixes**:
Fixes #748 

**Special notes for your reviewer**:
- The `DefaultMinAmount` may be  redundant, since we already have cache for the USD price

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

File: app/services/pricing/service.go [hunk 1]
```diff
@@ -324,9 +335,17 @@ func (s *Service) updatePriceInfoContainers(nativeAsset *asset.NativeAsset, toke
 			continue
 		}
 		wrappedAssetInfo, _ := s.assetsService.FungibleAssetInfo(networkId, wrappedToken)
+		
+		defaultMinAmount := tokenPriceInfo.DefaultMinAmount
```
Comment (Coiling-Dragon) [inline app/services/pricing/service.go:339]: Is it correct to get defaultMinAmount from tokenPriceInfo.DefaultMinAmount?
More likely not because decimals may be different, since this function updates the amount for wrapped tokens on other networks?

Maybe it is better to have defaultUsdPrice instead of defaultMinAmount, so when we implement the custom fees
the calculations will work relatively good for the special users also.

**Review by svetlio8 — CHANGES_REQUESTED** [review]
DCO check doesn't pass, please signed off the commits

**Review by svetlio8 — DISMISSED** [review]

File: app/services/pricing/service.go [hunk 2]
```diff
@@ -323,10 +334,19 @@ func (s *Service) updatePriceInfoContainers(nativeAsset *asset.NativeAsset, toke
...
 		wrappedMinAmountWithFee, err := s.calculateMinAmountWithFee(nativeAsset, wrappedAssetInfo.Decimals, tokenPriceInfo.UsdPrice)
 		if err != nil {
-			return err
+			s.logger.Errorf("Failed to calculate 'MinAmountWithFee' for asset: [%s]. Error: [%s]", wrappedToken, err)
+			if defaultMinAmount.Cmp(big.NewInt(0)) <= 0 {
+				err = fmt.Errorf("Default min_amount for asset: [%s] is not set. Error: [%s]", wrappedToken, err)
+				return err
```
Comment (rokn) [inline app/services/pricing/service.go:346]: nit: You can directly return the error here

**Review by svetlio8 — APPROVED** [review]

**Review by trayanm — DISMISSED** [review]

**Review by trayanm — APPROVED** [review]

**Review by svetlio8 — APPROVED** [review]

**Review by rokn — APPROVED** [review]
