### PR TITLE
Fix/read only logs

### LINKED ISSUE #832: Read only updates transfer to completed prematurely
The read only updates the status of transfer prematurely to COMPLETED and should update it only after the last transfer is completed(`mint-hts`)

### PR DESCRIPTION
**Pull request by Coiling-Dragon**
**Detailed description**:
- fixed wrong transaction status
- fixed endless loop, that was expecting debit transaction, that will never occur in bridge acc.

**Which issue(s) this PR fixes**:
Fixes #832 

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

File: app/process/handler/read-only/mint-hts/handler.go [hunk 1]
```diff
@@ -39,32 +39,43 @@ type Handler struct {
...
 }
 
 func NewHandler(
 	scheduleRepository repository.Schedule,
 	bridgeAccount string,
+	payerAccount string,
 	mirrorNode client.MirrorNode,
 	transfersService service.Transfers,
 	readOnlyService service.ReadOnly,
+	transferRepository repository.Transfer,
```
Comment (rokn) [inline app/process/handler/read-only/mint-hts/handler.go:57]: nit: I'd keep this near the other repository to keep things ordered, same for the fields of the struct

**Review by rokn — DISMISSED** [review]

**Review by rokn — APPROVED** [review]

**Review by rokn — APPROVED** [review]
